
import {
    Fingerprint,
    Baby,
    HeartHandshake,
    HeartCrack,
    User,
    Activity,
    FileText,
    Stamp,
    GraduationCap,
    Stethoscope,
    FileSignature,
    Sparkles,
    Scale,
    Scroll,
    Scissors,
    Cross,
    CalendarCheck
} from "lucide-react";

export interface DocumentData {
    id: string;
    slug: string;
    title: string;
    metaTitle: string;
    metaDescription: string;
    heroTitle: string;
    heroSubtitle: string;
    pricingTitle: string;
    slugHeroTitle: string;      // "Legalizamos tu/tus X en Cuba y te lo/los entregamos en España"
    processTitle: string;       // "Así gestionamos tus/tu/la..." — grammatically correct per doc
    comparisonSubtitle: string; // "Para que tus/tu/la..." — grammatically correct per doc
    icon: React.ElementType;
    shortDescription: string;
    isWhatsappAction?: boolean;
    heroImage?: string;  // imagen frontal específica del documento en el hero
}

export const documentsData: DocumentData[] = [
    {
        id: "antecedentes-penales",
        slug: "legalizacion-documentos-cubanos-antecedentes-penales",
        title: "Antecedentes Penales",
        heroTitle: "Legalización de Antecedentes Penales",
        heroSubtitle: "Documento indispensable para casi cualquier trámite de extranjería y nacionalidad en España.",
        pricingTitle: "Precios y tiempos de los Antecedentes Penales",
        slugHeroTitle: "Legalizamos tus Antecedentes Penales en Cuba y te los entregamos en España",
        processTitle: "Así gestionamos tus Antecedentes Penales",
        comparisonSubtitle: "Para que tus Antecedentes Penales sean aceptados en España, deben cumplir con estas 3 verificaciones.",
        metaTitle: "Antecedentes Penales Cuba: Legalización MINJUS y Consulado 2026",
        metaDescription: "Gestionamos tus Antecedentes Penales en Cuba. Legalización completa en MINJUS y Consulado de España. Envío internacional seguro.",
        icon: Scale,
        shortDescription: "Necesarios para casi cualquier trámite de extranjería en España.",
        heroImage: "/images/legalizaciones-hero-minjus.png",
    },
    {
        id: "certificado-nacimiento",
        slug: "legalizacion-documentos-cubanos-certificado-nacimiento",
        title: "Certificado de Nacimiento",
        heroTitle: "Legalización de Certificado de Nacimiento",
        heroSubtitle: "El documento base para tu expediente de nacionalidad o residencia.",
        pricingTitle: "Precios y tiempos del Certificado de Nacimiento",
        slugHeroTitle: "Legalizamos tu Certificado de Nacimiento en Cuba y te lo entregamos en España",
        processTitle: "Así gestionamos tu Certificado de Nacimiento",
        comparisonSubtitle: "Para que tu Certificado de Nacimiento sea aceptado en España, debe cumplir con estas 3 verificaciones.",
        metaTitle: "Certificado Nacimiento Cuba: Legalización para España 2026",
        metaDescription: "Obtención y legalización de Certificados de Nacimiento en Cuba. Servicio exprés MINJUS y Consulado. Entrega en tu domicilio.",
        icon: Scroll,
        shortDescription: "Para DNI, pasaporte y expedientes de extranjería.",
        heroImage: "/images/doc-certificado-nacimiento.png",
    },
    {
        id: "certificado-matrimonio",
        slug: "legalizacion-documentos-cubanos-certificado-matrimonio",
        title: "Certificado de Matrimonio",
        heroTitle: "Legalización de Certificado de Matrimonio",
        heroSubtitle: "Valida tu matrimonio cubano en España para reagrupación o registro.",
        pricingTitle: "Precios y tiempos del Certificado de Matrimonio",
        slugHeroTitle: "Legalizamos tu Certificado de Matrimonio en Cuba y te lo entregamos en España",
        processTitle: "Así gestionamos tu Certificado de Matrimonio",
        comparisonSubtitle: "Para que tu Certificado de Matrimonio sea aceptado en España, debe cumplir con estas 3 verificaciones.",
        metaTitle: "Certificado Matrimonio Cuba: Legalizar en MINJUS y Consulado",
        metaDescription: "Legalizamos tu Certificado de Matrimonio cubano para España. Trámite completo sin que tengas que viajar. Envío garantizado.",
        icon: HeartHandshake,
        shortDescription: "Para registro de matrimonio y reagrupación familiar.",
        heroImage: "/images/doc-certificado-matrimonio.png",
    },
    {
        id: "certificado-divorcio",
        slug: "legalizacion-documentos-cubanos-certificado-divorcio",
        title: "Certificado de Divorcio",
        heroTitle: "Legalización de Sentencia de Divorcio",
        heroSubtitle: "Reconocimiento de tu estado civil para nuevos trámites en España.",
        pricingTitle: "Precios y tiempos del Certificado de Divorcio",
        slugHeroTitle: "Legalizamos tu Certificado de Divorcio en Cuba y te lo entregamos en España",
        processTitle: "Así gestionamos tu Certificado de Divorcio",
        comparisonSubtitle: "Para que tu Certificado de Divorcio sea aceptado en España, debe cumplir con estas 3 verificaciones.",
        metaTitle: "Sentencia Divorcio Cuba: Exequátur y Legalización España",
        metaDescription: "Legalización de sentencias de divorcio y certificados en Cuba. Preparación para Exequátur en España. Asesoría experta.",
        icon: HeartCrack,
        shortDescription: "Necesario para nuevos matrimonios o parejas de hecho.",
        heroImage: "/images/doc-certificado-divorcio.png",
    },
    {
        id: "certificado-solteria",
        slug: "legalizacion-documentos-cubanos-certificado-solteria",
        title: "Certificado de Soltería",
        heroTitle: "Legalización de Fe de Soltería",
        heroSubtitle: "Demuestra tu capacidad legal para contraer matrimonio en España.",
        pricingTitle: "Precios y tiempos del Certificado de Soltería",
        slugHeroTitle: "Legalizamos tu Certificado de Soltería en Cuba y te lo entregamos en España",
        processTitle: "Así gestionamos tu Certificado de Soltería",
        comparisonSubtitle: "Para que tu Certificado de Soltería sea aceptado en España, debe cumplir con estas 3 verificaciones.",
        metaTitle: "Certificado Soltería Cuba: Legalización Consular para Matrimonio",
        metaDescription: "Obtén y legaliza tu Fe de Soltería en Cuba. Documento indispensable para casarse o hacerse pareja de hecho en España.",
        icon: User,
        shortDescription: "Requisito obligatorio para expedientes de matrimonio.",
        heroImage: "/images/doc-certificado-solteria.png",
    },
    {
        id: "certificado-defuncion",
        slug: "legalizacion-documentos-cubanos-certificado-defuncion",
        title: "Certificado de Defunción",
        heroTitle: "Legalización de Certificado de Defunción",
        heroSubtitle: "Trámites de herencias, pensiones y viudedad en España.",
        pricingTitle: "Precios y tiempos del Certificado de Defunción",
        slugHeroTitle: "Legalizamos el Certificado de Defunción en Cuba y te lo entregamos en España",
        processTitle: "Así gestionamos el Certificado de Defunción",
        comparisonSubtitle: "Para que el Certificado de Defunción sea aceptado en España, debe cumplir con estas 3 verificaciones.",
        metaTitle: "Certificado Defunción Cuba: Legalización para Herencias España",
        metaDescription: "Gestionamos certificados de defunción en Cuba legalizados para trámites de herencia y seguridad social en España.",
        icon: Cross,
        shortDescription: "Para trámites de herencias y pensiones de viudedad.",
        heroImage: "/images/doc-certificado-defuncion.png",
    },
    {
        id: "estado-conyugal",
        slug: "legalizacion-documentos-cubanos-estado-conyugal",
        title: "Certificado de Estado Conyugal",
        heroTitle: "Legalización de Estado Conyugal",
        heroSubtitle: "Acreditación de tu estado civil actual.",
        pricingTitle: "Precios y tiempos del Certificado de Estado Conyugal",
        slugHeroTitle: "Legalizamos tu Certificado de Estado Conyugal en Cuba y te lo entregamos en España",
        processTitle: "Así gestionamos tu Certificado de Estado Conyugal",
        comparisonSubtitle: "Para que tu Certificado de Estado Conyugal sea aceptado en España, debe cumplir con estas 3 verificaciones.",
        metaTitle: "Certificado Estado Conyugal Cuba: Legalización MINJUS 2026",
        metaDescription: "Legalizamos certificaciones de estado conyugal. Validez garantizada ante autoridades españolas.",
        icon: FileText,
        shortDescription: "Complementario a la fe de soltería en algunos casos.",
        heroImage: "/images/doc-certificado-matrimonio.png",
    },
    {
        id: "vigencia-matrimonio",
        slug: "legalizacion-documentos-cubanos-vigencia-matrimonio",
        title: "Vigencia de Matrimonio",
        heroTitle: "Legalización de Vigencia de Matrimonio",
        heroSubtitle: "Certificación actualizada de tu vínculo matrimonial.",
        pricingTitle: "Precios y tiempos de la Vigencia de Matrimonio",
        slugHeroTitle: "Legalizamos la Vigencia de Matrimonio en Cuba y te la entregamos en España",
        processTitle: "Así gestionamos la Vigencia de Matrimonio",
        comparisonSubtitle: "Para que la Vigencia de Matrimonio sea aceptada en España, debe cumplir con estas 3 verificaciones.",
        metaTitle: "Vigencia de Matrimonio Cuba: Legalización para España",
        metaDescription: "Solicita y legaliza la Vigencia de Matrimonio en Cuba. Trámite rápido y seguro con Gestoría HOL.",
        icon: CalendarCheck,
        shortDescription: "Prueba de que el matrimonio sigue siendo válido.",
        heroImage: "/images/doc-certificado-matrimonio.png",
    },
    {
        id: "documentos-academicos",
        slug: "legalizacion-documentos-cubanos-documentos-academicos",
        title: "Documentos Académicos",
        heroTitle: "Legalización de Títulos y Notas",
        heroSubtitle: "Homologación y equivalencia de estudios en España.",
        pricingTitle: "Precios y tiempos de Documentos Académicos",
        slugHeroTitle: "Legalizamos tus Documentos Académicos en Cuba y te los entregamos en España",
        processTitle: "Así gestionamos tus Documentos Académicos",
        comparisonSubtitle: "Para que tus Documentos Académicos sean aceptados en España, deben cumplir con estas 3 verificaciones.",
        metaTitle: "Legalizar Título Universitario Cuba: Homologación España 2026",
        metaDescription: "Legalización de títulos, notas y planes de estudio cubanos para homologación en España. Tarifas MINJUS actualizadas.",
        icon: GraduationCap,
        shortDescription: "Títulos, notas y programas para homologación.",
        heroImage: "/images/doc-academicos.png",
    },
    {
        id: "certificados-medicos",
        slug: "legalizacion-documentos-cubanos-certificados-medicos",
        title: "Certificados Médicos",
        heroTitle: "Legalización de Certificados Médicos",
        heroSubtitle: "Para visados de estudios, residencia y trabajo.",
        pricingTitle: "Precios y tiempos de Certificados Médicos",
        slugHeroTitle: "Legalizamos tus Certificados Médicos en Cuba y te los entregamos en España",
        processTitle: "Así gestionamos tus Certificados Médicos",
        comparisonSubtitle: "Para que tus Certificados Médicos sean aceptados en España, deben cumplir con estas 3 verificaciones.",
        metaTitle: "Certificado Médico Cuba: Legalización para Visados España",
        metaDescription: "Legalización de certificados médicos en MINSAP y MINJUS para trámites de extranjería y visados en el Consulado.",
        icon: Stethoscope,
        shortDescription: "Requisito para visados de residencia y estudios.",
        heroImage: "/images/doc-medicos.png",
    },
    {
        id: "poderes-notariales",
        slug: "legalizacion-documentos-cubanos-poderes-notariales",
        title: "Poderes Notariales",
        heroTitle: "Legalización de Poderes Notariales",
        heroSubtitle: "Validez de poderes cubanos en territorio español.",
        pricingTitle: "Precios y tiempos de Poderes Notariales",
        slugHeroTitle: "Legalizamos tus Poderes Notariales en Cuba y te los entregamos en España",
        processTitle: "Así gestionamos tus Poderes Notariales",
        comparisonSubtitle: "Para que tus Poderes Notariales sean aceptados en España, deben cumplir con estas 3 verificaciones.",
        metaTitle: "Poderes Notariales Cuba: Legalización para uso en España",
        metaDescription: "Legalizamos poderes especiales y generales otorgados en Cuba para que surtan efectos legales en España.",
        icon: FileSignature,
        shortDescription: "Para actuar en nombre de otra persona en España.",
        heroImage: "/images/doc-poderes-notariales.png",
    },
    {
        id: "otros-documentos",
        slug: "legalizacion-documentos-cubanos-otros-documentos",
        title: "Otros Documentos",
        heroTitle: "Legalización de Otros Documentos",
        heroSubtitle: "Consultar especificidades para otros trámites.",
        pricingTitle: "Precios y tiempos de Otros Documentos",
        slugHeroTitle: "Legalizamos tus documentos en Cuba y te los entregamos en España",
        processTitle: "Así gestionamos tus Otros Documentos",
        comparisonSubtitle: "Para que tus documentos sean aceptados en España, deben cumplir con estas 3 verificaciones.",
        metaTitle: "Legalización de Documentos Varios Cuba-España",
        metaDescription: "Servicio de legalización para cualquier otro documento notarial o registral cubano necesario en España.",
        icon: Sparkles,
        shortDescription: "Sentencias, actos de última voluntad y más.",
        isWhatsappAction: true,
    },
];

export function getDocumentBySlug(slug: string) {
    return documentsData.find(doc => doc.slug === slug);
}
